# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESKART_APP' do

platform :ios, ‘9.0’

pod 'KYDrawerController-ObjC'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~>3.8'

end